site_name: FRC Java Programming
repo_name: Example Project
repo_url: https://github.com/FRCTeam3255/FRC-Java-Tutorial/tree/remaster
edit_uri: https://github.com/FRCTeam3255/FRC-Java-Tutorial/edit/remaster/Docs_Source/docs/
site_author: Tayler Uva

# Theme
theme:
  name: 'material'
  custom_dir: 'theme'
  logo:
    icon: 'laptop'
  feature:
    tabs: false
extra_css: 
  - assets/css/sn.css
use_directory_urls: false

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - toc:
        permalink: "#"
        separator: "_"

# Navigation
nav:
- 'index.md'
- Learning the Basics:
  - 'basics/roboRIO.md'
  - 'basics/sensors.md'
  - 'basics/java_basics.md'
  - 'WPILib Programming Basics': 'missing.md'
- Dev Enviroment Setup:
  - 'Software Installation and Setup': 'missing.md'
  - 'Imaging the roboRIO': 'missing.md'
  - 'Setting-up the Robot Radio': 'missing.md'
- Programming an FRC Robot:
  - 'Part 1: Basic Driving Robot': 'missing.md'
  - 'Part 2: Pneumatics': 'missing.md'
  - 'Part 3: Sensors and Switches': 'missing.md'
  - 'Part 4: Dashboards': 'missing.md'
  - 'Part 5: RobotPreferences': 'missing.md'
  - 'Part 6: Autonomous Command': 'missing.md'
  - 'Part 7: PID': 'missing.md'
- 'More pages coming soon': 'missing.md'