site_name: FRC Java Programming
repo_name: Tutorial Bot
repo_url: https://github.com/FRCTeam3255/FRC-Java-Tutorial/tree/remaster
edit_uri: https://github.com/FRCTeam3255/FRC-Java-Tutorial/edit/remaster/Docs_Source/docs/
site_author: Tayler Uva

# Theme
theme:
  name: 'material'
  custom_dir: 'theme'
  icon:
    logo: 'material/laptop'
  features:
    - 'tabs'
  palette:
    primary: 'blue'
    accent: 'light blue'
    scheme: slate
extra_css: 
  # - assets/css/dark_theme.css
  # - assets/css/codehilite.css
  - assets/css/sn.css
use_directory_urls: false

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.betterem
  - pymdownx.tasklist
  - pymdownx.extra
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      css_class: 'codehilite'
  - toc:
        permalink: "#"

# Navigation
nav:
- Home:
  - 'index.md'
  - 'contributing.md'
- Programming Basics:
  - 'basics/roboRIO.md'
  - 'basics/sensors.md'
  - 'basics/java_basics.md'
  - 'basics/wpilib.md'
  - 'basics/vscode_tips.md'
  # - 'basics/driverstation_tips.md'
- FRC Development Environment Setup:
  - 'setup/install_software.md'
- FRC Programming:
  - 'programming/new_project.md'
  - 'programming/driving_robot.md'
  - 'programming/deploying.md'
  - 'programming/pneumatics.md'
  - 'programming/using_sensors.md'
  - 'programming/shuffleboard.md'
  - 'programming/robotpreferences.md'
  - 'programming/autonomous.md'
  # - 'programming/pid.md'
  # - 'programming/super_core.md'
- Version Control:
  - 'version_control/github.md'