site_name: FRC Java Programming
repo_name: Example Project
repo_url: https://github.com/FRCTeam3255/FRC-Java-Tutorial/tree/remaster
edit_uri: https://github.com/FRCTeam3255/FRC-Java-Tutorial/edit/remaster/Docs_Source/docs/
site_author: Tayler Uva

# Theme
theme:
  name: 'material'
  custom_dir: 'theme'
  logo:
    icon: 'laptop'
  feature:
    tabs: false
extra_css: 
  - assets/css/sn.css
use_directory_urls: false

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - toc:
        permalink: "#"
        separator: "_"

# Navigation
nav:
- 'index.md'
- Learning the Basics:
  - 'basics/roboRIO.md'
  - 'basics/sensors.md'
  - 'basics/java_basics.md'
  - 'basics/wpilib.md'
# - Dev Enviroment Setup:
# - Programming an FRC Robot: