# Navigation
nav:
- Home:
  - 'index.md'
  - 'why_software.md'
- Programming Basics:
  - 'basics/roboRIO.md'
  - 'basics/sensors.md'
  - 'basics/wpilib.md'
  - 'basics/java_basics.md'
  - 'basics/vscode_tips.md'
  # - 'basics/driverstation_tips.md'
- FRC Development Environment Setup:
  - 'setup/install_software.md'
  - 'setup/install_other.md'
  - 'setup/imaging_roboRIO.md'
- FRC Programming:
  - 'programming/new_project.md'
  - 'programming/driving_robot.md'
  - 'programming/deploying.md'
  - 'programming/using_sensors.md'
  - 'programming/pneumatics.md'
  - 'programming/shuffleboard.md'
  - 'programming/robotpreferences.md'
  - 'programming/autonomous.md'
  - 'programming/pid.md'
  # - 'programming/super_core.md'
- Example Subsystems:
  - 'examples/basic_elevator.md'
  - 'examples/basic_shooter.md'
  - 'examples/pid_elevator.md'
  - 'examples/pid_shooter.md'
- Version Control:
  - 'version_control/github.md'
- Improve the Documentation:
  - 'contributing.md'

# Setup
site_name: FRC Java Programming
repo_name: Tutorial Bot
repo_url: https://github.com/FRCTeam3255/FRC-Java-Tutorial/tree/main
edit_uri: https://github.com/FRCTeam3255/FRC-Java-Tutorial/edit/main/Docs_Source/docs/
site_author: Tayler Uva

# Theme
theme:
  name: 'readthedocs'
  favicon: assets/favicon.png
  icon:
    logo: assets/favicon.png
use_directory_urls: false

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.betterem
  - pymdownx.tasklist
  - pymdownx.extra
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      css_class: 'codehilite'
  - toc:
        permalink: "#"

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true

google_analytics:
  - UA-47256977-4
  - auto