name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - remaster
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-git-revision-date-plugin
      - run: pip install pip install mkdocs-minify-plugin
      - run: mkdocs gh-deploy --force
        working-directory: ./Docs_Source
